#!/usr/bin/python

import gobject
import dbus
import dbus.service
import sys

from dbus.mainloop.glib import DBusGMainLoop


class TestService(dbus.service.Object):

    def __init__(self, name):
        bus_name = dbus.service.BusName(
            'org.genivi.BootManager1.LegacyAppHandler.%s' % name,
            bus=dbus.SystemBus())
        object_path = '/org/genivi/BootManager1/LegacyAppHandler/%s' % name
        dbus.service.Object.__init__(self, bus_name, object_path)

    @dbus.service.method('org.genivi.BootManager1.LegacyAppHandler.Test')
    def hello(self):
        return "Hello World!"


if __name__ == '__main__':
    DBusGMainLoop(set_as_default=True)
    service = TestService(sys.argv[1])
    loop = gobject.MainLoop()
    loop.run()
